FROM  mongo:3.6.11-stretch

LABEL org.label-schema.build-date="2018-04-20T16:58:20Z"
LABEL org.label-schema.name = "an-todo-16022018 MONGO"
LABEL org.label-schema.vendor = "Singularity"
LABEL org.label-schema.version = "0.1.0"

COPY ./mongod.conf /etc/mongod.conf